name: tir-learner
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::genericrepeatfinder=1.0.2
  - bioconda::genometools-genometools=1.6.5
  - bioconda::blast=2.15.0
  - conda-forge::biopython=1.83
  - conda-forge::scikit-learn=1.4.1.post1
  - conda-forge::pandas=2.2.1
  - conda-forge::glob2=0.7
  - conda-forge::multiprocess=0.70.16
  - conda-forge::regex=2023.12.25
  - conda-forge::tensorflow=2.15.0
  - conda-forge::keras=2.15.0
  - conda-forge::swifter=1.4.0