name: run test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-test:
    name: ci-test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: tir-learner
          environment-file: environment.yml
          auto-activate-base: false
      - run: python3 TIR-Learner3/TIR-Learner.py --version
      - run: |
          python3 TIR-Learner3/TIR-Learner.py -f test/genome.fa -s others -t 2 -l 5000 -o ./
          sha256sum TIR-Learner-Result/* > hash.txt
          cmp hash.txt test/hash.txt --silent
